security: install Composer in specific channel
Install with a release version doesn't accept 2.2.

Composer setup script supports channel install.

A channel is important to get patched versions.

diff --git a/config/steps/composer.yml b/config/steps/composer.yml
--- a/config/steps/composer.yml
+++ b/config/steps/composer.yml
@@ -17,6 +17,31 @@
   get_url: url=https://getcomposer.org/download/{{symfony_composer_version}}/composer.phar dest={{symfony_composer_path}} mode=0755 validate_certs=no force=no
   when: symfony_composer_version is defined
 
+- name: Install composer {{symfony_composer_channel}}
+  shell: |
+    #!/bin/sh
+    
+    chdir {{symfony_composer_path}}
+  
+    # https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
+  
+    EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
+    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+    ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+    
+    if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
+    then
+    >&2 echo 'ERROR: Invalid installer checksum'
+    rm composer-setup.php
+    exit 1
+    fi
+  
+    php composer-setup.php --quiet --{{symfony_composer_channel}}
+    RESULT=$?
+    rm composer-setup.php
+    exit $RESULT
+  when: symfony_composer_channel is defined
+
 - name: Run composer install
   shell: chdir={{ansistrano_release_path.stdout}}
     export SYMFONY_ENV={{symfony_env}} APP_ENV={{symfony_env}} && {{symfony_php_path}} {{symfony_composer_path}} install {{symfony_composer_options}}
